### ISSUE TITLE
Testing Webcam: set up environment

### ISSUE THREAD

**Issue by jinzishuai** [jinzishuai/BackgroundMattingV2#1]
https://github.com/PeterL1n/BackgroundMattingV2/blob/master/inference_webcam.py

**Comment by jinzishuai** [comment]
# 1. Couldn't install `torch==1.7.0` on Windows

```
C:\ZeroBox\src\BackgroundMattingV2>pip install -r requirements.txt
Collecting kornia==0.4.1
  Downloading kornia-0.4.1-py2.py3-none-any.whl (225 kB)
     |████████████████████████████████| 225 kB 2.2 MB/s
Requirement already satisfied: tensorboard==2.3.0 in c:\users\jinzi\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from -r requirements.txt (line 2)) (2.3.0)
ERROR: Could not find a version that satisfies the requirement torch==1.7.0 (from -r requirements.txt (line 3)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.7.1)
ERROR: No matching distribution found for torch==1.7.0 (from -r requirements.txt (line 3))
WARNING: You are using pip version 20.2.3; however, version 20.3.3 is available.
You should consider upgrading via the 'C:\Users\jinzi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.

C:\ZeroBox\src\BackgroundMattingV2>pip show torch
Name: torch
Version: 1.6.0+cu101
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: c:\users\jinzi\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages
Requires: numpy, future
Required-by: torchvision

C:\ZeroBox\src\BackgroundMattingV2>
```

## Python-3.8.7

```
C:\ZeroBox\src\BackgroundMattingV2>python --version
Python 3.8.7
```

**Comment by jinzishuai** [comment]
## 1.1 similar problem on linux with conda

```
(bgm2) seki@xubuntu-20:~/src/BackgroundMattingV2$ pip install -r requirements.txt 
ERROR: Could not find a version that satisfies the requirement torch==1.7.0
ERROR: No matching distribution found for torch==1.7.0
```

**Comment by jinzishuai** [comment]
## Problem with python-3.9: worked with 3.8.5 on xubuntu-20

didn't work when I had
```
(bgm2) seki@xubuntu-20:~/src/BackgroundMattingV2$ python --version
Python 3.9.1
```

Worked after `conda install python=3.8`:
```
(bgm2) seki@xubuntu-20:~/src/BackgroundMattingV2$ python --version
Python 3.8.5
(bgm2) seki@xubuntu-20:~/src/BackgroundMattingV2$ pip --version
pip 20.3.3 from /home/seki/miniconda3/envs/bgm2/lib/python3.8/site-packages/pip (python 3.8)
(bgm2) seki@xubuntu-20:~/src/BackgroundMattingV2$ 
```

**Comment by jinzishuai** [comment]
# 2. Cannot run in vbox since it requires GPU

```
(bgm2) seki@xubuntu-20:~/src/BackgroundMattingV2$ python inference_webcam.py \
>         --model-type mattingrefine \
>         --model-backbone resnet50 \
>         --model-checkpoint Model/TorchScript/torchscript_mobilenetv2_fp16.pth \
>         --resolution 1280 720
Traceback (most recent call last):
  File "inference_webcam.py", line 137, in <module>
    model = model.cuda().eval()
  File "/home/seki/miniconda3/envs/bgm2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 463, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/seki/miniconda3/envs/bgm2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/seki/miniconda3/envs/bgm2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/seki/miniconda3/envs/bgm2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/home/seki/miniconda3/envs/bgm2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 463, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/seki/miniconda3/envs/bgm2/lib/python3.8/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
(bgm2) seki@xubuntu-20:~/src/BackgroundMattingV2$ 
```

**Comment by jinzishuai** [comment]
## windows python

* remove and install pip would get us python-3.9 and it didn't work
```
(bgm2) C:\ZeroBox\src\BackgroundMattingV2>pip --version
pip 20.3.3 from C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\pip (python 3.9)

(bgm2) C:\ZeroBox\src\BackgroundMattingV2>python --version
Python 3.9.1
```
* reinstall python=3.8 with `conda install python=3.8`: still not working
```
(bgm2) C:\ZeroBox\src\BackgroundMattingV2>python --version
Python 3.8.5

(bgm2) C:\ZeroBox\src\BackgroundMattingV2>pip --version
pip 20.3.3 from C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\pip (python 3.8)

(bgm2) C:\ZeroBox\src\BackgroundMattingV2>pip install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement torch==1.7.0
ERROR: No matching distribution found for torch==1.7.0
```

**Comment by jinzishuai** [comment]
# Use conda to install

```
conda install -c pytorch pytorch=1.7.0
```

Now that pytorch=1.7 is installed, we got a new error
```
(bgm2) C:\ZeroBox\src\BackgroundMattingV2>pip install -r requirements.txt
Requirement already satisfied: torch==1.7.0 in c:\users\jinzi\miniconda3\envs\bgm2\lib\site-packages (from -r requirements.txt (line 3)) (1.7.0)
ERROR: Could not find a version that satisfies the requirement torchvision==0.8.1
ERROR: No matching distribution found for torchvision==0.8.1
```

Solution: `conda install -c pytorch torchvision==0.8.1`


Then all packages are installed `pip install -r requirements.txt`

**Comment by jinzishuai** [comment]
# 3. GPU Driver is too old

```
(bgm2) C:\ZeroBox\src\BackgroundMattingV2> python inference_webcam.py --model-type mattingrefine --model-backbone resnet50 --model-checkpoint TorchScript\torchscript_mobilenetv2_fp16.pth --resolution 1280 720
Traceback (most recent call last):
  File "inference_webcam.py", line 137, in <module>
    model = model.cuda().eval()
  File "C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\torch\nn\modules\module.py", line 463, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\torch\nn\modules\module.py", line 359, in _apply
    module._apply(fn)
  File "C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\torch\nn\modules\module.py", line 359, in _apply
    module._apply(fn)
  File "C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\torch\nn\modules\module.py", line 381, in _apply
    param_applied = fn(param)
  File "C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\torch\nn\modules\module.py", line 463, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\torch\cuda\__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: The NVIDIA driver on your system is too old (found version 10020). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.
```

**Comment by jinzishuai** [comment]
## cuda-11.0 was installed

```
(bgm2) C:\ZeroBox\src\BackgroundMattingV2>conda list pytorch
# packages in environment at C:\Users\jinzi\miniconda3\envs\bgm2:
#
# Name                    Version                   Build  Channel
pytorch                   1.7.0           py3.8_cuda110_cudnn8_0    pytorch

(bgm2) C:\ZeroBox\src\BackgroundMattingV2>conda list torchvision
# packages in environment at C:\Users\jinzi\miniconda3\envs\bgm2:
#
# Name                    Version                   Build  Channel
torchvision               0.8.1                py38_cu110    pytorch
```
while the driver is still version 10.2.


## 3.1 Install cuda-10.2

```
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
```

**Comment by jinzishuai** [comment]
# 4. Couldn't load .pth file

```
(bgm2) C:\ZeroBox\src\BackgroundMattingV2> python inference_webcam.py --model-type mattingrefine --model-backbone resnet50 --model-checkpoint TorchScript\torchscript_mobilenetv2_fp16.pth --resolution 1280 720
C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\torch\serialization.py:589: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  warnings.warn("'torch.load' received a zip file that looks like a TorchScript archive"
Traceback (most recent call last):
  File "inference_webcam.py", line 138, in <module>
    model.load_state_dict(torch.load(args.model_checkpoint), strict=False)
  File "C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\torch\nn\modules\module.py", line 1025, in load_state_dict
    state_dict = state_dict.copy()
  File "C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\torch\jit\_script.py", line 558, in __getattr__
    return super(RecursiveScriptModule, self).__getattr__(attr)
  File "C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\torch\jit\_script.py", line 288, in __getattr__
    return super(ScriptModule, self).__getattr__(attr)
  File "C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\torch\nn\modules\module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'RecursiveScriptModule' object has no attribute 'copy'
```

**Comment by jinzishuai** [comment]
## Specify all version

```
(bgm2) C:\ZeroBox\src\BackgroundMattingV2>conda install pytorch=1.7.0 torchvision=0.8.1 cudatoolkit=10.2 -c pytorch
```

**Comment by jinzishuai** [comment]
![image](https://user-images.githubusercontent.com/1074685/103319821-5d3a1b80-49f0-11eb-82a3-21b0babfe0bd.png)

**Comment by jinzishuai** [comment]
## Solution: Use PyTorch Model instead of TorchScript: Worked

![image](https://user-images.githubusercontent.com/1074685/103321600-b3f72380-49f7-11eb-97d6-0204b905c677.png)

**Comment by jinzishuai** [comment]
https://github.com/PeterL1n/BackgroundMattingV2/issues/17

**Comment by jinzishuai** [comment]
# 5. Using inference_webcam.py

```
(bgm2) C:\ZeroBox\src\BackgroundMattingV2>python inference_webcam.py -h
usage: inference_webcam.py [-h] --model-type {mattingbase,mattingrefine} --model-backbone {resnet101,resnet50,mobilenetv2} [--model-backbone-scale MODEL_BACKBONE_SCALE] --model-checkpoint MODEL_CHECKPOINT
                           [--model-refine-mode {full,sampling,thresholding}] [--model-refine-sample-pixels MODEL_REFINE_SAMPLE_PIXELS] [--model-refine-threshold MODEL_REFINE_THRESHOLD] [--hide-fps]
                           [--resolution width height]

Inference from web-cam

optional arguments:
  -h, --help            show this help message and exit
  --model-type {mattingbase,mattingrefine}
  --model-backbone {resnet101,resnet50,mobilenetv2}
  --model-backbone-scale MODEL_BACKBONE_SCALE
  --model-checkpoint MODEL_CHECKPOINT
  --model-refine-mode {full,sampling,thresholding}
  --model-refine-sample-pixels MODEL_REFINE_SAMPLE_PIXELS
  --model-refine-threshold MODEL_REFINE_THRESHOLD
  --hide-fps
  --resolution width height
```

**Comment by jinzishuai** [comment]
## 5.1 Basic Key Controls

* `b`: to set the background
* `q`: exit
![image](https://user-images.githubusercontent.com/1074685/103322050-cd996a80-49f9-11eb-8194-61e53c91e2f2.png)

**Comment by jinzishuai** [comment]
## 5.2 mattingbase is worse than mattingrefine

The previous result is `--model-type mattingrefine`

For `python inference_webcam.py --model-type mattingbase --model-backbone resnet101  --resolution 1280 720 --model-checkpoint PyTorch\pytorch_resnet101.pth` is worse

![image](https://user-images.githubusercontent.com/1074685/103322229-9081a800-49fa-11eb-85aa-99091a4cdb56.png)

**Comment by jinzishuai** [comment]
> # 2. Cannot run in vbox since it requires GPU

Note that unlike the other reference code, there is no `--device` option
