### ISSUE TITLE
Testing inference_video.py

### ISSUE THREAD

**Issue by jinzishuai** [jinzishuai/BackgroundMattingV2#2]
# Usage

```
(bgm2) C:\ZeroBox\src\BackgroundMattingV2>python inference_video.py -h
usage: inference_video.py [-h] --model-type {mattingbase,mattingrefine} --model-backbone {resnet101,resnet50,mobilenetv2}
                          [--model-backbone-scale MODEL_BACKBONE_SCALE] --model-checkpoint MODEL_CHECKPOINT [--model-refine-mode {full,sampling,thresholding}]
                          [--model-refine-sample-pixels MODEL_REFINE_SAMPLE_PIXELS] [--model-refine-threshold MODEL_REFINE_THRESHOLD]
                          [--model-refine-kernel-size MODEL_REFINE_KERNEL_SIZE] --video-src VIDEO_SRC --video-bgr VIDEO_BGR
                          [--video-resize VIDEO_RESIZE VIDEO_RESIZE] [--device {cpu,cuda}] [--preprocess-alignment] --output-dir OUTPUT_DIR --output-types
                          {com,pha,fgr,err,ref} [{com,pha,fgr,err,ref} ...] [--output-format {video,image_sequences}]

Inference video

optional arguments:
  -h, --help            show this help message and exit
  --model-type {mattingbase,mattingrefine}
  --model-backbone {resnet101,resnet50,mobilenetv2}
  --model-backbone-scale MODEL_BACKBONE_SCALE
  --model-checkpoint MODEL_CHECKPOINT
  --model-refine-mode {full,sampling,thresholding}
  --model-refine-sample-pixels MODEL_REFINE_SAMPLE_PIXELS
  --model-refine-threshold MODEL_REFINE_THRESHOLD
  --model-refine-kernel-size MODEL_REFINE_KERNEL_SIZE
  --video-src VIDEO_SRC
  --video-bgr VIDEO_BGR
  --video-resize VIDEO_RESIZE VIDEO_RESIZE
  --device {cpu,cuda}
  --preprocess-alignment
  --output-dir OUTPUT_DIR
  --output-types {com,pha,fgr,err,ref} [{com,pha,fgr,err,ref} ...]
  --output-format {video,image_sequences}
```

**Comment by jinzishuai** [comment]
# Test Run

* extract background: https://github.com/jinzishuai/personal-repo/issues/205
* run
```
(bgm2) C:\ZeroBox\src\BackgroundMattingV2> python inference_video.py --model-type mattingrefine --model-backbone resnet101 --model-checkpoint PyTorch\pytorch_resnet101.pth --video-src ..\..\group15B_Short.avi --video-bgr ..\..\background_group15B.png --output-dir output --output-type com fgr pha err ref
Directory output already exists. Override? [Y/N]: Y
 25%|█████████████████████████████▊                                                                                          | 557/2241 [02:16<06:53,  4.07it/s]
Traceback (most recent call last):
  File "inference_video.py", line 178, in <module>
    for src, bgr in tqdm(DataLoader(dataset, batch_size=1, pin_memory=True)):
  File "C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\tqdm\std.py", line 1171, in __iter__
    for obj in iterable:
  File "C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\torch\utils\data\dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\ZeroBox\src\BackgroundMattingV2\dataset\zip.py", line 17, in __getitem__
    x = tuple(d[idx % len(d)] for d in self.datasets)
  File "C:\ZeroBox\src\BackgroundMattingV2\dataset\zip.py", line 17, in <genexpr>
    x = tuple(d[idx % len(d)] for d in self.datasets)
  File "C:\ZeroBox\src\BackgroundMattingV2\dataset\video.py", line 27, in __getitem__
    raise IndexError(f'Idx: {idx} out of length: {len(self)}')
IndexError: Idx: 557 out of length: 2241
```
* output videos

![image](https://user-images.githubusercontent.com/1074685/103325088-6682b280-4a07-11eb-9003-599aab386f59.png)

**Comment by jinzishuai** [comment]
## 1.1 video only has 557 frames

```
C:\ZeroBox> ffmpeg -i .\group15B_Short.avi -map 0:v:0 -c copy -f null -
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.1 (GCC) 20200726
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, avi, from '.\group15B_Short.avi':
  Metadata:
    encoder         : Lavf58.20.100
  Duration: 00:01:52.05, start: 0.000000, bitrate: 768 kb/s
    Stream #0:0: Video: mpeg4 (Simple Profile) (FMP4 / 0x34504D46), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 764 kb/s, 20 fps, 20 tbr, 20 tbn, 20 tbc
Output #0, null, to 'pipe:':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: mpeg4 (Simple Profile) (FMP4 / 0x34504D46), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 764 kb/s, 20 fps, 20 tbr, 20 tbn, 20 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
frame=  557 fps=0.0 q=-1.0 Lsize=N/A time=00:01:52.05 bitrate=N/A speed=1.3e+04x
video:10447kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
```

**Comment by jinzishuai** [comment]
https://user-images.githubusercontent.com/1074685/103325557-7e5b3600-4a09-11eb-875a-a4b029a521bc.mp4

**Comment by jinzishuai** [comment]
# Linux on CPU
## still not working with `--device cpu`

```
(bgm2) seki@xubuntu-20:~/src/BackgroundMattingV2$ python inference_video.py --model-type mattingrefine --model-backbone resnet101 --model-checkpoint Model/PyTorch/pytorch_resnet101.pth --video-src ../zerobox-v2/resource/group15B_Short.avi --video-bgr ../zerobox-v2/resource/background_group15B.png --output-dir output_video_group15B --output-type com fgr pha err ref --device cpu
/home/seki/miniconda3/envs/bgm2/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "inference_video.py", line 128, in <module>
    model.load_state_dict(torch.load(args.model_checkpoint), strict=False)
  File "/home/seki/miniconda3/envs/bgm2/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/seki/miniconda3/envs/bgm2/lib/python3.8/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
  File "/home/seki/miniconda3/envs/bgm2/lib/python3.8/site-packages/torch/serialization.py", line 845, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/seki/miniconda3/envs/bgm2/lib/python3.8/site-packages/torch/serialization.py", line 834, in load_tensor
    loaded_storages[key] = restore_location(storage, location)
  File "/home/seki/miniconda3/envs/bgm2/lib/python3.8/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/seki/miniconda3/envs/bgm2/lib/python3.8/site-packages/torch/serialization.py", line 151, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/seki/miniconda3/envs/bgm2/lib/python3.8/site-packages/torch/serialization.py", line 135, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

**Comment by jinzishuai** [comment]
## worked with this patch

```diff
(bgm2) seki@xubuntu-20:~/src/BackgroundMattingV2$ git diff
diff --git a/inference_video.py b/inference_video.py
index 97da5d7..c7c04e8 100644
--- a/inference_video.py
+++ b/inference_video.py
@@ -111,6 +111,7 @@ class ImageSequenceWriter:
 
 
 device = torch.device(args.device)
+print(f"device={device}")
 
 # Load model
 if args.model_type == 'mattingbase':
@@ -125,7 +126,7 @@ if args.model_type == 'mattingrefine':
         args.model_refine_kernel_size)
 
 model = model.to(device).eval()
-model.load_state_dict(torch.load(args.model_checkpoint), strict=False)
+model.load_state_dict(torch.load(args.model_checkpoint, map_location=device), strict=False)
```

**Comment by jinzishuai** [comment]
## still with warning

I think my pytorch installation might be wrong (should not have CUDA since I don't have the GPU hardware)
![image](https://user-images.githubusercontent.com/1074685/103389616-30a80180-4acd-11eb-91d4-1ca12e234a6e.png)

**Comment by jinzishuai** [comment]
fixed in https://github.com/PeterL1n/BackgroundMattingV2/pull/21
