### ISSUE TITLE
Testing inference_images.py

### ISSUE THREAD

**Issue by jinzishuai** [jinzishuai/BackgroundMattingV2#3]
https://github.com/jinzishuai/BackgroundMattingV2/blob/master/inference_images.py

# Usage

```
(bgm2) C:\ZeroBox\src\BackgroundMattingV2>python inference_images.py -h
usage: inference_images.py [-h] --model-type {mattingbase,mattingrefine} --model-backbone {resnet101,resnet50,mobilenetv2}
                           [--model-backbone-scale MODEL_BACKBONE_SCALE] --model-checkpoint MODEL_CHECKPOINT [--model-refine-mode {full,sampling,thresholding}]
                           [--model-refine-sample-pixels MODEL_REFINE_SAMPLE_PIXELS] [--model-refine-threshold MODEL_REFINE_THRESHOLD]
                           [--model-refine-kernel-size MODEL_REFINE_KERNEL_SIZE] --images-src IMAGES_SRC --images-bgr IMAGES_BGR [--device {cpu,cuda}]
                           [--preprocess-alignment] --output-dir OUTPUT_DIR --output-types {com,pha,fgr,err,ref} [{com,pha,fgr,err,ref} ...] [-y]

Inference images

optional arguments:
  -h, --help            show this help message and exit
  --model-type {mattingbase,mattingrefine}
  --model-backbone {resnet101,resnet50,mobilenetv2}
  --model-backbone-scale MODEL_BACKBONE_SCALE
  --model-checkpoint MODEL_CHECKPOINT
  --model-refine-mode {full,sampling,thresholding}
  --model-refine-sample-pixels MODEL_REFINE_SAMPLE_PIXELS
  --model-refine-threshold MODEL_REFINE_THRESHOLD
  --model-refine-kernel-size MODEL_REFINE_KERNEL_SIZE
  --images-src IMAGES_SRC
  --images-bgr IMAGES_BGR
  --device {cpu,cuda}
  --preprocess-alignment
  --output-dir OUTPUT_DIR
  --output-types {com,pha,fgr,err,ref} [{com,pha,fgr,err,ref} ...]
  -y

```

**Comment by jinzishuai** [comment]
# 1. prepare images by running zerobox on group15_Short.avi

* Source folder: `C:\ZeroBox\src\zerobox-v2\output\group15B_Short.avi`
* Copy the original files to `C:\ZeroBox\src\BackgroundMattingV2\Group15BOriginals`

**Comment by jinzishuai** [comment]
# 2. nn not defined

```
(bgm2) C:\ZeroBox\src\BackgroundMattingV2> python inference_images.py --model-type mattingrefine --model-backbone resnet101 --model-checkpoint PyTorch\pytorch_resnet101.pth --images-src Group15BOriginals --images-bgr Group15BBackground --output-dir output1 --output-type com fgr pha  --model-refine-mode full
Traceback (most recent call last):
  File "inference_images.py", line 97, in <module>
    HomographicAlignment() if args.preprocess_alignment else A.PairApply(nn.Identity()),
NameError: name 'nn' is not defined

(bgm2) C:\ZeroBox\src\BackgroundMattingV2>
```

**Comment by jinzishuai** [comment]
# 3. With https://github.com/PeterL1n/BackgroundMattingV2/pull/18 and copies of background for each image

![image](https://user-images.githubusercontent.com/1074685/103326464-afd60080-4a0d-11eb-9539-34435f91ea89.png)

```
(bgm2) C:\ZeroBox\src\BackgroundMattingV2> python inference_images.py --model-type mattingrefine --model-backbone resnet101 --model-checkpoint PyTorch\pytorch_resnet101.pth --images-src Group15BOriginals --images-bgr Group15BBackground --output-dir output1 --output-type com fgr pha  --model-refine-mode full
Directory output1 already exists. Override? [Y/N]: Y
  0%|                                                                                                                                    | 0/11 [00:15<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\torch\utils\data\dataloader.py", line 872, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Users\jinzi\miniconda3\envs\bgm2\lib\queue.py", line 178, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "inference_images.py", line 123, in <module>
    for i, (src, bgr) in enumerate(tqdm(dataloader)):
  File "C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\tqdm\std.py", line 1171, in __iter__
    for obj in iterable:
  File "C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\torch\utils\data\dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\torch\utils\data\dataloader.py", line 1024, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\jinzi\miniconda3\envs\bgm2\lib\site-packages\torch\utils\data\dataloader.py", line 885, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 27048, 46952, 51548) exited unexpectedly
```

**Comment by jinzishuai** [comment]
## homographic alignment

* https://github.com/PeterL1n/BackgroundMattingV2/blob/97e2df124d0fa96eb7f101961a2eb806cdd25049/inference_utils.py#L6
* https://docs.opencv.org/master/d9/dab/tutorial_homography.html

**Comment by jinzishuai** [comment]
## even one image has an out of memory problem
![image](https://user-images.githubusercontent.com/1074685/103328176-f24f0b80-4a14-11eb-8a8f-9fd427dedfba.png)

**Comment by jinzishuai** [comment]
same problem
* renaming images to 0.png
* use the same images from https://drive.google.com/drive/folders/1XM50AYuveTxpfzDtAal1z9RIEEqlalOv
* use mobilenetv2
* use cpu
![image](https://user-images.githubusercontent.com/1074685/103392520-8d121d80-4adb-11eb-9cd5-13ad70b245ab.png)

**Comment by jinzishuai** [comment]
# Finally Worked with PR-#7

```
(bgm2) C:\ZeroBox\src\BackgroundMattingV2>python inference_images.py --model-type mattingrefine --model-backbone resnet101 --model-checkpoint PyTorch\pytorch_resnet101.pth --images-src Group15BOriginals --images-bgr Group15BBackground --output-dir output-images-group15B --output-type com fgr pha
100%|██████████████████████████████████████████████████████████████████████████████████| 11/11 [00:05<00:00,  2.12it/s]
```

* using identical background images
![image](https://user-images.githubusercontent.com/1074685/103420874-b7ed8780-4b56-11eb-95db-87bb2734444b.png)
* input
![image](https://user-images.githubusercontent.com/1074685/103421048-9b058400-4b57-11eb-95f0-61aba635fc10.png)

* output
![image](https://user-images.githubusercontent.com/1074685/103421092-d86a1180-4b57-11eb-93a3-e26af6ea9be1.png)


same resolution as inputs:
```
$ file output-images-group15B/com/*
output-images-group15B/com/Camera0_202009141728031_original.png: PNG image data, 1080 x 1920, 8-bit/color RGBA, non-interlaced
output-images-group15B/com/Camera0_202009141728182_original.png: PNG image data, 1080 x 1920, 8-bit/color RGBA, non-interlaced
output-images-group15B/com/Camera0_202009141728273_original.png: PNG image data, 1080 x 1920, 8-bit/color RGBA, non-interlaced
output-images-group15B/com/Camera0_202009141728362_original.png: PNG image data, 1080 x 1920, 8-bit/color RGBA, non-interlaced
output-images-group15B/com/Camera0_202009141728442_original.png: PNG image data, 1080 x 1920, 8-bit/color RGBA, non-interlaced
output-images-group15B/com/Camera0_202009141728512_original.png: PNG image data, 1080 x 1920, 8-bit/color RGBA, non-interlaced
output-images-group15B/com/Camera0_202009141728572_original.png: PNG image data, 1080 x 1920, 8-bit/color RGBA, non-interlaced
output-images-group15B/com/Camera0_202009141729040_original.png: PNG image data, 1080 x 1920, 8-bit/color RGBA, non-interlaced
output-images-group15B/com/Camera0_202009141729108_original.png: PNG image data, 1080 x 1920, 8-bit/color RGBA, non-interlaced
output-images-group15B/com/Camera0_202009141729170_original.png: PNG image data, 1080 x 1920, 8-bit/color RGBA, non-interlaced
output-images-group15B/com/Camera0_202009141729219_original.png: PNG image data, 1080 x 1920, 8-bit/color RGBA, non-interlaced
```

**Comment by jinzishuai** [comment]
# Test on Linux with CPU

```
(bgm2) seki@xubuntu-20:~/src/BackgroundMattingV2$ python inference_images.py --model-type mattingrefine --model-backbone resnet101 --model-checkpoint Model/PyTorch/pytorch_resnet101.pth --images-src Group15BOriginals --images-bgr Group15BBackground --output-dir output-images-group15B --output-type com fgr pha --device cpu
Traceback (most recent call last):
  File "inference_images.py", line 90, in <module>
    model.load_state_dict(torch.load(args.model_checkpoint), strict=False)
  File "/home/seki/miniconda3/envs/bgm2/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/seki/miniconda3/envs/bgm2/lib/python3.8/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
  File "/home/seki/miniconda3/envs/bgm2/lib/python3.8/site-packages/torch/serialization.py", line 845, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/seki/miniconda3/envs/bgm2/lib/python3.8/site-packages/torch/serialization.py", line 834, in load_tensor
    loaded_storages[key] = restore_location(storage, location)
  File "/home/seki/miniconda3/envs/bgm2/lib/python3.8/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/seki/miniconda3/envs/bgm2/lib/python3.8/site-packages/torch/serialization.py", line 151, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/seki/miniconda3/envs/bgm2/lib/python3.8/site-packages/torch/serialization.py", line 135, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

```

**Comment by jinzishuai** [comment]
## Worked with the same CPU patch

```
(bgm2) seki@xubuntu-20:~/src/BackgroundMattingV2$ python inference_images.py --model-type mattingrefine --model-backbone resnet101 --model-checkpoint Model/PyTorch/pytorch_resnet101.pth --images-src Group15BOriginals --images-bgr Group15BBackground --output-dir output-images-group15B --output-type com fgr pha --device cpu
  0%|                                                                                                                   | 0/11 [00:00<?, ?it/s][W NNPACK.cpp:80] Could not initialize NNPACK! Reason: Unsupported hardware.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:25<00:00,  2.27s/it]
(bgm2) seki@xubuntu-20:~/src/BackgroundMattingV2$ git diff
diff --git a/inference_images.py b/inference_images.py
index ff73ad4..4acb770 100644
--- a/inference_images.py
+++ b/inference_images.py
@@ -87,7 +87,7 @@ if args.model_type == 'mattingrefine':
         args.model_refine_kernel_size)
 
 model = model.to(device).eval()
-model.load_state_dict(torch.load(args.model_checkpoint), strict=False)
+model.load_state_dict(torch.load(args.model_checkpoint, map_location=device), strict=False)
 
 
 # Load images
(bgm2) seki@xubuntu-20:~/src/BackgroundMattingV2$ 

```

**Comment by jinzishuai** [comment]
CPU support is fixed by https://github.com/PeterL1n/BackgroundMattingV2/pull/26
